client:
 peers:
  peer1:
    host: "localhost"
    port: 7051
    event_host: "localhost"
    event_port: 7053

  peer2:
    host: "localhost"
    port: 7056

 tls:
  enabled: false
  certificate:
  serverhostoverride:

 security:
  enabled: true
  hashAlgorithm: "SHA2"
  level: 256

 tcert:
  batch:
    size: 200

 orderer:
  host: "localhost"
  port: 7050

 logging:
  level: info

 msp:
  id: "DEFAULT"
  url: "http://localhost:7054"
  clientPath: "../integration_test/test_resources/config"

 keystore:
  path: "/tmp/keystore"